/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package canchas.ucuenca.edu.org.UI;

import canchas.ucuenca.edu.org.Model.Cancha;
import canchas.ucuenca.edu.org.Model.Encargado;
import canchas.ucuenca.edu.org.Service.CanchaSrv;
import canchas.ucuenca.edu.org.Service.EncargadoSrv;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author mauriciop
 */
public class AgregarCanchaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AgregarCanchaJPanel
     */
    private ModoEdicion modoEdicion;
    public AgregarCanchaJPanel() {
        
        initComponents();
        modoEdicion = ModoEdicion.AGREGAR;
        cargarEncargados();//usado para combobox
    }
    
    private void cargarEncargados(){
        EncargadoSrv encargado = new EncargadoSrv();
        String[] lista = encargado.listar().split("_"); //lista de todos los encargados
        String[] encargados = null;     //lista para almacenar cada atributo del encargado
        for(int i=0;i<lista.length;i++){
            encargados = lista[i].split(",");
            //System.out.println(encargados[0]);
            encargadosCBOX.addItem(encargados[0]);
        }       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreTxt = new javax.swing.JTextField();
        direccionTxt = new javax.swing.JTextField();
        valortxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        aceptarBtn = new javax.swing.JButton();
        cancelarBtn = new javax.swing.JButton();
        codigoTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        encargadosCBOX = new javax.swing.JComboBox();

        jLabel6.setText("Encargado:");

        jLabel2.setText("Codigo:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Direccion:");

        jLabel5.setText("Valor:");

        aceptarBtn.setText("Aceptar");
        aceptarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarBtnActionPerformed(evt);
            }
        });

        cancelarBtn.setText("Cancelar");
        cancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("EB Garamond 12", 1, 18)); // NOI18N
        jLabel1.setText("Agregar Cancha");

        encargadosCBOX.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(direccionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(valortxt, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(codigoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(aceptarBtn)
                                .addGap(75, 75, 75)
                                .addComponent(cancelarBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(encargadosCBOX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 86, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(codigoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(direccionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(valortxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(encargadosCBOX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptarBtn)
                    .addComponent(cancelarBtn))
                .addGap(13, 13, 13))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarBtnActionPerformed
        // TODO add your handling code here:
        String codigo = codigoTxt.getText();
        String nombre = nombreTxt.getText();
        String direccion = direccionTxt.getText();
        String valor = valortxt.getText();
        
        String mensaje=null;
        
        try {
            Double valorDo = Double.parseDouble(valor);
            
            CanchaSrv service = new CanchaSrv();
            
            EncargadoSrv encargadoSRV = new EncargadoSrv();
            Encargado encar = encargadoSRV.obtenerEncargado((String) encargadosCBOX.getSelectedItem());
            
            
            
            if(modoEdicion.equals(ModoEdicion.AGREGAR)){
                
                //System.out.println(encar.cedula()+encar.nombre());
                service.crearCancha(codigo, nombre, direccion, valorDo, encar);
                
                service.guardar();
                
                mensaje = "Cancha agregada correctamente!!";
                
                //this.setVisible(false);
                
            }
            else if(modoEdicion.equals(ModoEdicion.MODIFICAR)){
                service.modificarCancha(codigo, nombre, direccion, valorDo, encar);
                
                service.guardar();
                mensaje = "Cancha modificada correctamente!!";
                
                //this.setVisible(false);
            }
            
            else if(modoEdicion.equals(ModoEdicion.ELIMINAR)){
                service.eliminarCancha(codigo);
                service.guardar();
                mensaje = "Cancha eliminada correctamente!!";
                //
            }
            
            JOptionPane.showMessageDialog(null, mensaje);
            this.hide();
        } catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "Error en los campos!!");
        }catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
        
        
    }//GEN-LAST:event_aceptarBtnActionPerformed

    private void cancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_cancelarBtnActionPerformed

    public void ponerDatos(Cancha cancha){
        codigoTxt.setText(cancha.codigo());
        nombreTxt.setText(cancha.nombre());
        direccionTxt.setText(cancha.direccion());
        valortxt.setText(String.valueOf(cancha.valor()));
        
        
        codigoTxt.setEditable(false);
        codigoTxt.setBackground(Color.GRAY);
    }
    
    public void modificarBoton(){
        aceptarBtn.setText("Modificiar");
        modoEdicion = ModoEdicion.MODIFICAR;
        
    }
    
    public void eliminarBoton(){
        aceptarBtn.setText("Eliminar");
        modoEdicion = ModoEdicion.ELIMINAR;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarBtn;
    private javax.swing.JButton cancelarBtn;
    private javax.swing.JTextField codigoTxt;
    private javax.swing.JTextField direccionTxt;
    private javax.swing.JComboBox encargadosCBOX;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JTextField valortxt;
    // End of variables declaration//GEN-END:variables
}
