/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package canchas.ucuenca.edu.org.UI;

import canchas.ucuenca.edu.org.Dao.EncargadoDao;
import canchas.ucuenca.edu.org.Model.Encargado;
import canchas.ucuenca.edu.org.Service.EncargadoSrv;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mauriciop
 */
public class GestionEncargadoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form GestionEncargadoJPanel
     */
    DefaultTableModel modelo = new DefaultTableModel();
    public GestionEncargadoJPanel() {
        initComponents();
        tablaEncargadosTBL.getTableHeader().setReorderingAllowed(false);
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        modificarBtn = new javax.swing.JButton();
        eliminarBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEncargadosTBL = new javax.swing.JTable();
        salirBtn = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("EB Garamond 12", 1, 18)); // NOI18N
        jLabel1.setText("Encargado");

        modificarBtn.setText("Modificar");
        modificarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarBtnActionPerformed(evt);
            }
        });

        eliminarBtn.setText("Eliminar");
        eliminarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarBtnActionPerformed(evt);
            }
        });

        tablaEncargadosTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cedula", "Nombre", "Apellido", "Edad"
            }
        ));
        jScrollPane1.setViewportView(tablaEncargadosTBL);

        salirBtn.setText("Salir");
        salirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(modificarBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(eliminarBtn)
                        .addGap(110, 110, 110))))
            .addGroup(layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(salirBtn)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modificarBtn)
                    .addComponent(eliminarBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(salirBtn)
                .addContainerGap(46, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void modificarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarBtnActionPerformed
        // TODO add your handling code here:
        int a = tablaEncargadosTBL.getSelectedRow();
        String cedula = (String) modelo.getValueAt(a, 0);

        try {
            Encargado encargado ;
            encargado = EncargadoDao.getEncargado(cedula);

            AgregarEncargadoJPanel agregar = new AgregarEncargadoJPanel();
            agregar.ponerDatos(encargado);
            agregar.modificarBoton();

            GestionJFrame nueva = new GestionJFrame();
            nueva.agregarVentana(agregar);
            nueva.setVisible(true);

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }finally{
            this.hide();
        }

    }//GEN-LAST:event_modificarBtnActionPerformed

    private void eliminarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBtnActionPerformed
        // TODO add your handling code here:
        int a = tablaEncargadosTBL.getSelectedRow();
        String codigo = (String) modelo.getValueAt(a, 0);

        try {
            Encargado encargado ;
            encargado = EncargadoDao.getEncargado(codigo);

            AgregarEncargadoJPanel agregar = new AgregarEncargadoJPanel();
            agregar.ponerDatos(encargado);
            agregar.eliminarBoton();

            GestionJFrame nueva = new GestionJFrame();
            nueva.agregarVentana(agregar);
            nueva.setVisible(true);

        } catch (Exception e) {
        }finally{
            this.hide();
        }

    }//GEN-LAST:event_eliminarBtnActionPerformed

    private void salirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBtnActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_salirBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton eliminarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton modificarBtn;
    private javax.swing.JButton salirBtn;
    private javax.swing.JTable tablaEncargadosTBL;
    // End of variables declaration//GEN-END:variables

    private void cargarTabla() {
        
        limpiarTabla();
        try {
            modelo = (DefaultTableModel) tablaEncargadosTBL.getModel();
            EncargadoSrv servi = new EncargadoSrv();
            
            String[] lista = servi.listar().split("_");
            String[] canchas = null;
            
            for (int i = 0; i<lista.length; i++) {
                canchas = lista[i].split(",");
                
                
                modelo.addRow(canchas);
            }
            
            tablaEncargadosTBL.setModel(modelo);
            
        } catch (Exception e) {
        }
        
    }
    
    private void limpiarTabla(){
        modelo = (DefaultTableModel) tablaEncargadosTBL.getModel();
        int a =  modelo.getRowCount();
        
        for (int i = 0; i < a; i++) {
            modelo.removeRow(0);
        }
    }
}
