/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package canchas.ucuenca.edu.org.UI;

/**
 *
 * @author mauriciop
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JScrollPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        agregarCanchaBtn = new javax.swing.JMenuItem();
        listaCanchasBtn = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        agregarEncargadoBtn = new javax.swing.JMenuItem();
        listaEncargadosBtn = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        agregarClienteBtn = new javax.swing.JMenuItem();
        listaClientesBtn = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        agregarArbitroBtn = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Canchas ");

        jMenu6.setText("Gestion Canchas");

        agregarCanchaBtn.setText("Agregar Cancha");
        agregarCanchaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarCanchaBtnActionPerformed(evt);
            }
        });
        jMenu6.add(agregarCanchaBtn);

        listaCanchasBtn.setText("Canchas");
        listaCanchasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaCanchasBtnActionPerformed(evt);
            }
        });
        jMenu6.add(listaCanchasBtn);

        jMenu1.add(jMenu6);

        jMenu7.setText("Gestion Encargados");

        agregarEncargadoBtn.setText("Agregar Encargado");
        agregarEncargadoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarEncargadoBtnActionPerformed(evt);
            }
        });
        jMenu7.add(agregarEncargadoBtn);

        listaEncargadosBtn.setText("Encargados");
        listaEncargadosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaEncargadosBtnActionPerformed(evt);
            }
        });
        jMenu7.add(listaEncargadosBtn);

        jMenu1.add(jMenu7);

        jMenu8.setText("Gestion Clientes");

        agregarClienteBtn.setText("Agregar Cliente");
        agregarClienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarClienteBtnActionPerformed(evt);
            }
        });
        jMenu8.add(agregarClienteBtn);

        listaClientesBtn.setText("Clientes");
        listaClientesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaClientesBtnActionPerformed(evt);
            }
        });
        jMenu8.add(listaClientesBtn);

        jMenu1.add(jMenu8);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem1.setText("jMenuItem1");
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("jMenuItem2");
        jMenu2.add(jMenuItem2);

        agregarArbitroBtn.setText("Agregar Arbitro");
        agregarArbitroBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarArbitroBtnActionPerformed(evt);
            }
        });
        jMenu2.add(agregarArbitroBtn);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edit");

        jMenuItem4.setText("jMenuItem1");
        jMenu3.add(jMenuItem4);

        jMenuItem5.setText("jMenuItem2");
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Edit");

        jMenuItem6.setText("jMenuItem1");
        jMenu4.add(jMenuItem6);

        jMenuItem7.setText("jMenuItem2");
        jMenu4.add(jMenuItem7);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Edit");

        jMenuItem8.setText("jMenuItem1");
        jMenu5.add(jMenuItem8);

        jMenuItem9.setText("jMenuItem2");
        jMenu5.add(jMenuItem9);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarArbitroBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarArbitroBtnActionPerformed
        // TODO add your handling code here:
        AgregarArbitroJPanel agregarArbitroJPanel = new AgregarArbitroJPanel();
        contenedor.setViewportView(agregarArbitroJPanel);
    }//GEN-LAST:event_agregarArbitroBtnActionPerformed

    private void agregarCanchaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarCanchaBtnActionPerformed
        // TODO add your handling code here:
        AgregarCanchaJPanel agregarCanchaJPanel = new AgregarCanchaJPanel();
        contenedor.setViewportView(agregarCanchaJPanel);
        
    }//GEN-LAST:event_agregarCanchaBtnActionPerformed

    private void agregarEncargadoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarEncargadoBtnActionPerformed
        // TODO add your handling code here:
        AgregarEncargadoJPanel encar = new AgregarEncargadoJPanel();
        contenedor.setViewportView(encar);
    }//GEN-LAST:event_agregarEncargadoBtnActionPerformed

    private void listaEncargadosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaEncargadosBtnActionPerformed
        // TODO add your handling code here:
        GestionEncargadoJPanel gestion = new GestionEncargadoJPanel();
        contenedor.setViewportView(gestion);
    }//GEN-LAST:event_listaEncargadosBtnActionPerformed

    private void agregarClienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarClienteBtnActionPerformed
        // TODO add your handling code here:
        AgregarClienteJPanel cliente = new AgregarClienteJPanel();
        contenedor.setViewportView(cliente);
        
    }//GEN-LAST:event_agregarClienteBtnActionPerformed

    private void listaCanchasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaCanchasBtnActionPerformed
        // TODO add your handling code here:
        GestionCanchasJPanel canchas = new GestionCanchasJPanel();
        contenedor.setViewportView(canchas);
    }//GEN-LAST:event_listaCanchasBtnActionPerformed

    private void listaClientesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaClientesBtnActionPerformed
        // TODO add your handling code here:
        GestionClienteJPanel clientes = new GestionClienteJPanel();
        contenedor.setViewportView(clientes);
    }//GEN-LAST:event_listaClientesBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem agregarArbitroBtn;
    private javax.swing.JMenuItem agregarCanchaBtn;
    private javax.swing.JMenuItem agregarClienteBtn;
    private javax.swing.JMenuItem agregarEncargadoBtn;
    private javax.swing.JScrollPane contenedor;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem listaCanchasBtn;
    private javax.swing.JMenuItem listaClientesBtn;
    private javax.swing.JMenuItem listaEncargadosBtn;
    // End of variables declaration//GEN-END:variables
}
